In [1]:
import dask.dataframe as dd
from dask.distributed import Client

In [11]:
%%time
youtube = dd.read_csv('Youtube*-*.csv')

CPU times: user 9.29 ms, sys: 963 µs, total: 10.3 ms
Wall time: 8.79 ms


In [12]:
%%time
youtube

Dask DataFrame Structure:
              COMMENT_ID  AUTHOR    DATE CONTENT  CLASS
npartitions=5                                          
                  object  object  object  object  int64
                     ...     ...     ...     ...    ...
...                  ...     ...     ...     ...    ...
                     ...     ...     ...     ...    ...
                     ...     ...     ...     ...    ...
Dask Name: from-delayed, 15 tasks

In [17]:
%%time
youtube.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^ ﻿   
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .﻿   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [9]:
%%time
youtube.info()

<class 'dask.dataframe.core.DataFrame'>
Columns: 5 entries, COMMENT_ID to CLASS
dtypes: object(4), int64(1)

In [36]:
%%time
print(len(youtube))

1956
CPU times: user 170 ms, sys: 0 ns, total: 170 ms
Wall time: 156 ms


In [22]:
%%time
spam_comment = youtube.groupby('CLASS')
spam_comment.count()

Dask DataFrame Structure:
              COMMENT_ID AUTHOR   DATE CONTENT
npartitions=1                                 
                   int64  int64  int64   int64
                     ...    ...    ...     ...
Dask Name: dataframe-groupby-count-agg, 21 tasks

In [37]:
%%time
spam_messages = youtube[youtube['CLASS'] == 1]
print(len(spam_messages))

1005
CPU times: user 177 ms, sys: 0 ns, total: 177 ms
Wall time: 161 ms


In [38]:
%%time
legit_messages = youtube[youtube['CLASS'] == 0]
print(len(legit_messages))

951
CPU times: user 179 ms, sys: 0 ns, total: 179 ms
Wall time: 163 ms


**There are 1005 Spam messages and 951 comments**

In [29]:
%%time
youtube['CONTENT'] = youtube['CONTENT'].str.lower()
youtube.head()

CPU times: user 30.1 ms, sys: 0 ns, total: 30.1 ms
Wall time: 28.4 ms


In [31]:
%%time
youtube['check'] = youtube['CONTENT'].str.contains('check')

CPU times: user 4.48 ms, sys: 0 ns, total: 4.48 ms
Wall time: 4.17 ms


In [45]:
spam_check = spam_messages[spam_messages['CONTENT'].str.contains('check')]

print(len(spam_check))

461


In [46]:
legit_check = legit_messages[legit_messages['CONTENT'].str.contains('check')]

print(len(legit_check))

19


In [48]:
client = Client(n_workers=19)
client

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/bokeh/core.py:57: UserWarning: 
Port 8787 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn('\n' + msg)


<Client: scheduler='tcp://127.0.0.1:40329' processes=19 cores=19>


# Part 2. Big data options
You've been introduced to a variety of platforms (AWS SageMaker, AWS EMR, Databricks), libraries (Numba, Dask, MapReduce, Spark), and languages (Python, SQL, Scala, Java) that can "scale up" or "scale out" for faster processing of big data.

Write a paragraph comparing some of these technology options. For example, you could describe which technology you may personally prefer to use, in what circumstances, for what reasons.

AWS seems far easier to use than Databricks. AWS, though it costs money, provides more memory than Databricks. I can push my code to GitHub right in AWS. Since we've been using a lot of jupyter notebooks, we were already used to that. So AWS Sagemaker is most comfortable for me. Dask is not all that different from python. At least I've not learned enough yet to see a ton of differences. It does make dataframes easier to read if there are multiple data frames.Dask does work with Big Data while python, though it can was not designed for that purpose. 

Numba has been very useful in one of my current blogs I'm writing. With fractals and other visuals using a ton of math, Numba works well.

Spark is a little frustrating. It is close enough to python that I forget what command I need to use. My mind goes right to Python and then I'm trying to translate it into spark. Scala I could do without. Scala so far has been very confusing for me and does not seem logical. The all capitals in some places is something that has not been a habit so I am moving slower in solving things. I again am thinking in Python and then trying to translate into SCALA.